### ISSUE TITLE
7zip might be a better format for the reports

### ISSUE THREAD

**Issue by yoavweiss** [Webdevdata/webdevdata.org#1]
I've downloaded the 518MB zip, unzipped and compressed using 7zip. It turned into a 370MB file. 
Compressing as 7zip could reduce @stevefaulkner's hosting bill by 30% :)

**Comment by marcoscaceres** [comment]
is that with the 7zip format or is that using deflate? The only sucky thing about 7zip is that it's not supported out of the box.

**Comment by yoavweiss** [comment]
I used the 7z format. I agree on the "extra install" suckiness. 
Maybe offer 2 download files, so that people can choose their preferred format?

**Comment by marcoscaceres** [comment]
Closing as won't fix.
