### ISSUE TITLE
Move downloader code

### ISSUE THREAD

**Issue by marcoscaceres** [Webdevdata/webdevdata.org#16]
We should move the downloader code to it's own repo. Reusing the website repo and having a gh-pages branch for the website is not great.

**Comment by marcoscaceres** [comment]
Moved here:
 https://github.com/Webdevdata/fetcher

@yoavweiss, feel free to rename.

**Comment by yoavweiss** [comment]
Fetcher in the rye???

**Comment by marcoscaceres** [comment]
heh... I like that ;)
