### ISSUE TITLE
collect references/sources for stats

### ISSUE THREAD

**Issue by nwtn** [Webdevdata/webdevdata.org#17]
This has been a pain point for me for awhile, and something I've been mulling over. [@brucel's tweet this morning](https://twitter.com/brucel/status/380650888248823808) clarified my thinking.

I think we should collect and collate relevant stats for web devs, as well as citations. For example, [the zoom thing](https://github.com/igrigorik/http-client-hints/issues/16) @jonathantneal references (though the citation is 404ing for me right now). I always read all these super interesting, useful things, and then immediately lose track of them.

We could maybe do something like stats.webdevdata.org, and do a weekly or monthly roundup.

**Comment by marcoscaceres** [comment]
We don't have the ability to collect such data... not without running either a plugin or asking a browser vendor to provide some telemetry. Even with a plugin, could we detect the the zoom level?

**Comment by nwtn** [comment]
Sorry, I don't mean collect the data directly from users, I mean collect reported data from other sources + citations that we can reference. Some other examples would be the mobile stats that @lukew [occasionally posts on his blog](http://www.lukew.com/ff/entry.asp?1563).

**Comment by marcoscaceres** [comment]
ah. Sure, we can do the same we did with RICG. (http://wiki.responsiveimages.org/)

**Comment by marcoscaceres** [comment]
ok, so conclusion is to start collecting in the Wiki.
