### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by hober** [Webdevdata/webdevdata.org#2]
A couple of thoughts on naming:
- The zip files should all be named something like webdevdata.org-YYYY-MM.zip, so that it's obvious to people where the data came from and how stale it is.
- When unzipped, the resulting directory name should be something like webdevdata.org-YYYY-MM, for the same reason.

**Comment by marcoscaceres** [comment]
great suggestions. Certainly something we should do for the next release!

**Comment by yoavweiss** [comment]
Should be resolved once https://github.com/yoavweiss/webdevdata.org/commit/6053bf758a17ebc51a5742a20e521d53fd7c2ab9 is merged

**Comment by yoavweiss** [comment]
Can we close?
