### ISSUE TITLE
Include full HTTP response

### ISSUE THREAD

**Issue by zcorpan** [Webdevdata/webdevdata.org#4]
It would be useful if the files included the full HTTP response, not just the response body.

**Comment by marcoscaceres** [comment]
This would be really nice. @stevefaulkner does the crawler you are using support such a thing?

**Comment by yoavweiss** [comment]
Should be fixed in https://github.com/yoavweiss/webdevdata.org/commit/33a7aaa439a26a797d20583973d993f3ca144937

**Comment by yoavweiss** [comment]
Can we close?
